services:
  db:
    container_name: HitonicHi_postgresql
    image: postgres:18
    environment:
      POSTGRES_DB: Hitonichi
      POSTGRES_USER: Hitonichi_user
      POSTGRES_PASSWORD: Hitonichi_pass
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - "5432:5432"
volumes:
  db_data:
