# PHP + FPM
FROM php:8.3-fpm

# 必要なパッケージ
RUN apt-get update && apt-get install -y \
    nginx \
    git \
    unzip \
    libpq-dev \
    libzip-dev \
    && docker-php-ext-install pdo pdo_mysql pdo_pgsql zip

# Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# 作業ディレクトリ
WORKDIR /var/www/html

# Laravel をコピー
COPY backend/ /var/www/html/

# Nginx 設定
COPY nginx.conf /etc/nginx/nginx.conf

# 権限設定（超重要）
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 775 storage bootstrap/cache

# Composer install
RUN composer install --no-dev --optimize-autoloader

# ポート
EXPOSE 80

# 起動コマンド
CMD service nginx start && php-fpm

#start.sh起動
CMD ["/start.sh"]
